/* soapccuentaProxy.cpp
   Generated by gSOAP 2.8.0 from wsCCuenta.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#include "soapccuentaProxy.h"

ccuentaProxy::ccuentaProxy(const char *cIPWebService, int iPuerto, short iTimeOut)
{	ccuentaProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT, cIPWebService, iPuerto, iTimeOut);
}

ccuentaProxy::ccuentaProxy(const struct soap &_soap) : soap(_soap)
{ }

ccuentaProxy::ccuentaProxy(soap_mode iomode)
{	ccuentaProxy_init(iomode, iomode);
}

ccuentaProxy::ccuentaProxy(soap_mode imode, soap_mode omode)
{	ccuentaProxy_init(imode, omode);
}

void ccuentaProxy::ccuentaProxy_init(soap_mode imode, soap_mode omode, const char *cIPWebService, int iPuerto, short iTimeOut)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;

	recv_timeout = iTimeOut;
	send_timeout = iTimeOut;
	connect_timeout = iTimeOut;
	
	memset( cUrlEndPoint, 0, sizeof( cUrlEndPoint ) );	

	sprintf( cUrlEndPoint, "http://%s:%d", cIPWebService, iPuerto);
	soap_endpoint = cUrlEndPoint;
	
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns2", "urn:ccuenta", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	this->namespaces = namespaces;
}

ccuentaProxy::~ccuentaProxy()
{ }

void ccuentaProxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void ccuentaProxy::soap_noheader()
{	header = NULL;
}

const SOAP_ENV__Fault *ccuentaProxy::soap_fault()
{	return this->fault;
}

const char *ccuentaProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *ccuentaProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int ccuentaProxy::soap_close_socket()
{	return soap_closesock(this);
}

void ccuentaProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
void ccuentaProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}

char *ccuentaProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int ccuentaProxy::leerClienteCoppel(int numerocliente, char *cIpCartera, struct ns2__leerClienteCoppelResponse &_param_1)
{	struct soap *soap = this;
	struct ns2__leerClienteCoppel soap_tmp_ns2__leerClienteCoppel;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.27.113.11:20534/";
	soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__leerClienteCoppel.numerocliente = numerocliente;
	soap_tmp_ns2__leerClienteCoppel.cIpCartera = cIpCartera;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__leerClienteCoppel(soap, &soap_tmp_ns2__leerClienteCoppel);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__leerClienteCoppel(soap, &soap_tmp_ns2__leerClienteCoppel, "ns2:leerClienteCoppel", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__leerClienteCoppel(soap, &soap_tmp_ns2__leerClienteCoppel, "ns2:leerClienteCoppel", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_1)
		return soap_closesock(soap);
	soap_default_ns2__leerClienteCoppelResponse(soap, &_param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns2__leerClienteCoppelResponse(soap, &_param_1, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ccuentaProxy::leerDatosCliente(int numerocliente, char *tipoconsulta, char *cIpCartera, struct ns2__leerDatosClienteResponse &_param_2)
{	struct soap *soap = this;
	struct ns2__leerDatosCliente soap_tmp_ns2__leerDatosCliente;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.27.113.11:20534/";
	soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__leerDatosCliente.numerocliente = numerocliente;
	soap_tmp_ns2__leerDatosCliente.tipoconsulta = tipoconsulta;
	soap_tmp_ns2__leerDatosCliente.cIpCartera = cIpCartera;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__leerDatosCliente(soap, &soap_tmp_ns2__leerDatosCliente);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__leerDatosCliente(soap, &soap_tmp_ns2__leerDatosCliente, "ns2:leerDatosCliente", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__leerDatosCliente(soap, &soap_tmp_ns2__leerDatosCliente, "ns2:leerDatosCliente", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_2)
		return soap_closesock(soap);
	soap_default_ns2__leerDatosClienteResponse(soap, &_param_2);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns2__leerDatosClienteResponse(soap, &_param_2, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ccuentaProxy::leerDomicilioCliente(int numerocliente, char *cIpCartera, struct ns2__leerDomicilioClienteResponse &_param_3)
{	struct soap *soap = this;
	struct ns2__leerDomicilioCliente soap_tmp_ns2__leerDomicilioCliente;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.27.113.11:20534/";
	soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__leerDomicilioCliente.numerocliente = numerocliente;
	soap_tmp_ns2__leerDomicilioCliente.cIpCartera = cIpCartera;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__leerDomicilioCliente(soap, &soap_tmp_ns2__leerDomicilioCliente);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__leerDomicilioCliente(soap, &soap_tmp_ns2__leerDomicilioCliente, "ns2:leerDomicilioCliente", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__leerDomicilioCliente(soap, &soap_tmp_ns2__leerDomicilioCliente, "ns2:leerDomicilioCliente", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_3)
		return soap_closesock(soap);
	soap_default_ns2__leerDomicilioClienteResponse(soap, &_param_3);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns2__leerDomicilioClienteResponse(soap, &_param_3, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ccuentaProxy::leerCuentasCliente(int numerocliente, char *Fecha, char *cIpCartera, struct ns2__leerCuentasClienteResponse &_param_4)
{	struct soap *soap = this;
	struct ns2__leerCuentasCliente soap_tmp_ns2__leerCuentasCliente;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.27.113.11:20534/";
	soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__leerCuentasCliente.numerocliente = numerocliente;
	soap_tmp_ns2__leerCuentasCliente.Fecha = Fecha;
	soap_tmp_ns2__leerCuentasCliente.cIpCartera = cIpCartera;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__leerCuentasCliente(soap, &soap_tmp_ns2__leerCuentasCliente);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__leerCuentasCliente(soap, &soap_tmp_ns2__leerCuentasCliente, "ns2:leerCuentasCliente", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__leerCuentasCliente(soap, &soap_tmp_ns2__leerCuentasCliente, "ns2:leerCuentasCliente", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_4)
		return soap_closesock(soap);
	soap_default_ns2__leerCuentasClienteResponse(soap, &_param_4);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns2__leerCuentasClienteResponse(soap, &_param_4, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ccuentaProxy::leerCuentaCliente(int numerocliente, char *Fecha, char *tipoconsulta, char *cIpCartera, struct ns2__leerCuentaClienteResponse &_param_5)
{	struct soap *soap = this;
	struct ns2__leerCuentaCliente soap_tmp_ns2__leerCuentaCliente;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.27.113.11:20534/";
	soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__leerCuentaCliente.numerocliente = numerocliente;
	soap_tmp_ns2__leerCuentaCliente.Fecha = Fecha;
	soap_tmp_ns2__leerCuentaCliente.tipoconsulta = tipoconsulta;
	soap_tmp_ns2__leerCuentaCliente.cIpCartera = cIpCartera;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__leerCuentaCliente(soap, &soap_tmp_ns2__leerCuentaCliente);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__leerCuentaCliente(soap, &soap_tmp_ns2__leerCuentaCliente, "ns2:leerCuentaCliente", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__leerCuentaCliente(soap, &soap_tmp_ns2__leerCuentaCliente, "ns2:leerCuentaCliente", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_5)
		return soap_closesock(soap);
	soap_default_ns2__leerCuentaClienteResponse(soap, &_param_5);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns2__leerCuentaClienteResponse(soap, &_param_5, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ccuentaProxy::leerImportesTotalesCliente(int numerocliente, char *Fecha, char *cIpCartera, struct ns2__leerImportesTotalesClienteResponse &_param_6)
{	struct soap *soap = this;
	struct ns2__leerImportesTotalesCliente soap_tmp_ns2__leerImportesTotalesCliente;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.27.113.11:20534/";
	soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__leerImportesTotalesCliente.numerocliente = numerocliente;
	soap_tmp_ns2__leerImportesTotalesCliente.Fecha = Fecha;
	soap_tmp_ns2__leerImportesTotalesCliente.cIpCartera = cIpCartera;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__leerImportesTotalesCliente(soap, &soap_tmp_ns2__leerImportesTotalesCliente);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__leerImportesTotalesCliente(soap, &soap_tmp_ns2__leerImportesTotalesCliente, "ns2:leerImportesTotalesCliente", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__leerImportesTotalesCliente(soap, &soap_tmp_ns2__leerImportesTotalesCliente, "ns2:leerImportesTotalesCliente", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_6)
		return soap_closesock(soap);
	soap_default_ns2__leerImportesTotalesClienteResponse(soap, &_param_6);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns2__leerImportesTotalesClienteResponse(soap, &_param_6, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ccuentaProxy::leerImporteCandidatosPrestamos(int numerocliente, char *Fecha, int Tienda, int ciudad, char *cIpCartera, struct ns2__leerImporteCandidatosPrestamosResponse &_param_7)
{	struct soap *soap = this;
	struct ns2__leerImporteCandidatosPrestamos soap_tmp_ns2__leerImporteCandidatosPrestamos;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.27.113.11:20534/";
	soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__leerImporteCandidatosPrestamos.numerocliente = numerocliente;
	soap_tmp_ns2__leerImporteCandidatosPrestamos.Fecha = Fecha;
	soap_tmp_ns2__leerImporteCandidatosPrestamos.Tienda = Tienda;
	soap_tmp_ns2__leerImporteCandidatosPrestamos.ciudad = ciudad;
	soap_tmp_ns2__leerImporteCandidatosPrestamos.cIpCartera = cIpCartera;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__leerImporteCandidatosPrestamos(soap, &soap_tmp_ns2__leerImporteCandidatosPrestamos);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__leerImporteCandidatosPrestamos(soap, &soap_tmp_ns2__leerImporteCandidatosPrestamos, "ns2:leerImporteCandidatosPrestamos", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__leerImporteCandidatosPrestamos(soap, &soap_tmp_ns2__leerImporteCandidatosPrestamos, "ns2:leerImporteCandidatosPrestamos", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_7)
		return soap_closesock(soap);
	soap_default_ns2__leerImporteCandidatosPrestamosResponse(soap, &_param_7);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns2__leerImporteCandidatosPrestamosResponse(soap, &_param_7, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ccuentaProxy::leerMargenCredito(int numerocliente, char *Fecha, int Tienda, int ciudad, char *cIpCartera, struct ns2__leerMargenCreditoResponse &_param_8)
{	struct soap *soap = this;
	struct ns2__leerMargenCredito soap_tmp_ns2__leerMargenCredito;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.27.113.11:20534/";
	soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__leerMargenCredito.numerocliente = numerocliente;
	soap_tmp_ns2__leerMargenCredito.Fecha = Fecha;
	soap_tmp_ns2__leerMargenCredito.Tienda = Tienda;
	soap_tmp_ns2__leerMargenCredito.ciudad = ciudad;
	soap_tmp_ns2__leerMargenCredito.cIpCartera = cIpCartera;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__leerMargenCredito(soap, &soap_tmp_ns2__leerMargenCredito);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__leerMargenCredito(soap, &soap_tmp_ns2__leerMargenCredito, "ns2:leerMargenCredito", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__leerMargenCredito(soap, &soap_tmp_ns2__leerMargenCredito, "ns2:leerMargenCredito", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_8)
		return soap_closesock(soap);
	soap_default_ns2__leerMargenCreditoResponse(soap, &_param_8);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns2__leerMargenCreditoResponse(soap, &_param_8, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ccuentaProxy::leerConvenios(int numerocliente, char *Fecha, char *cIpCartera, struct ns2__leerConveniosResponse &_param_9)
{	struct soap *soap = this;
	struct ns2__leerConvenios soap_tmp_ns2__leerConvenios;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.27.113.11:20534/";
	soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__leerConvenios.numerocliente = numerocliente;
	soap_tmp_ns2__leerConvenios.Fecha = Fecha;
	soap_tmp_ns2__leerConvenios.cIpCartera = cIpCartera;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__leerConvenios(soap, &soap_tmp_ns2__leerConvenios);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__leerConvenios(soap, &soap_tmp_ns2__leerConvenios, "ns2:leerConvenios", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__leerConvenios(soap, &soap_tmp_ns2__leerConvenios, "ns2:leerConvenios", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_9)
		return soap_closesock(soap);
	soap_default_ns2__leerConveniosResponse(soap, &_param_9);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns2__leerConveniosResponse(soap, &_param_9, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ccuentaProxy::leerCantidadCuentasActivas(int numerocliente, char *Fecha, char *cIpCartera, struct ns2__leerCantidadCuentasActivasResponse &_param_10)
{	struct soap *soap = this;
	struct ns2__leerCantidadCuentasActivas soap_tmp_ns2__leerCantidadCuentasActivas;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.27.113.11:20534/";
	soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__leerCantidadCuentasActivas.numerocliente = numerocliente;
	soap_tmp_ns2__leerCantidadCuentasActivas.Fecha = Fecha;
	soap_tmp_ns2__leerCantidadCuentasActivas.cIpCartera = cIpCartera;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__leerCantidadCuentasActivas(soap, &soap_tmp_ns2__leerCantidadCuentasActivas);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__leerCantidadCuentasActivas(soap, &soap_tmp_ns2__leerCantidadCuentasActivas, "ns2:leerCantidadCuentasActivas", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__leerCantidadCuentasActivas(soap, &soap_tmp_ns2__leerCantidadCuentasActivas, "ns2:leerCantidadCuentasActivas", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_10)
		return soap_closesock(soap);
	soap_default_ns2__leerCantidadCuentasActivasResponse(soap, &_param_10);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns2__leerCantidadCuentasActivasResponse(soap, &_param_10, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ccuentaProxy::leerCuentaCliente01(int numerocliente, char *Fecha, char *tipoconsulta, char *cIpCartera, struct ns2__leerCuentaCliente01Response &_param_11)
{	struct soap *soap = this;
	struct ns2__leerCuentaCliente01 soap_tmp_ns2__leerCuentaCliente01;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.27.113.11:20534/";
	soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__leerCuentaCliente01.numerocliente = numerocliente;
	soap_tmp_ns2__leerCuentaCliente01.Fecha = Fecha;
	soap_tmp_ns2__leerCuentaCliente01.tipoconsulta = tipoconsulta;
	soap_tmp_ns2__leerCuentaCliente01.cIpCartera = cIpCartera;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__leerCuentaCliente01(soap, &soap_tmp_ns2__leerCuentaCliente01);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__leerCuentaCliente01(soap, &soap_tmp_ns2__leerCuentaCliente01, "ns2:leerCuentaCliente01", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__leerCuentaCliente01(soap, &soap_tmp_ns2__leerCuentaCliente01, "ns2:leerCuentaCliente01", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_11)
		return soap_closesock(soap);
	soap_default_ns2__leerCuentaCliente01Response(soap, &_param_11);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns2__leerCuentaCliente01Response(soap, &_param_11, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ccuentaProxy::leerCuentasCliente01(int numerocliente, char *Fecha, char *cIpCartera, struct ns2__leerCuentasCliente01Response &_param_12)
{	struct soap *soap = this;
	struct ns2__leerCuentasCliente01 soap_tmp_ns2__leerCuentasCliente01;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.27.113.11:20534/";
	soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__leerCuentasCliente01.numerocliente = numerocliente;
	soap_tmp_ns2__leerCuentasCliente01.Fecha = Fecha;
	soap_tmp_ns2__leerCuentasCliente01.cIpCartera = cIpCartera;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__leerCuentasCliente01(soap, &soap_tmp_ns2__leerCuentasCliente01);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__leerCuentasCliente01(soap, &soap_tmp_ns2__leerCuentasCliente01, "ns2:leerCuentasCliente01", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__leerCuentasCliente01(soap, &soap_tmp_ns2__leerCuentasCliente01, "ns2:leerCuentasCliente01", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_12)
		return soap_closesock(soap);
	soap_default_ns2__leerCuentasCliente01Response(soap, &_param_12);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns2__leerCuentasCliente01Response(soap, &_param_12, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ccuentaProxy::leerImportesTotalesCliente01(int numerocliente, char *Fecha, char *cIpCartera, struct ns2__leerImportesTotalesCliente01Response &_param_13)
{	struct soap *soap = this;
	struct ns2__leerImportesTotalesCliente01 soap_tmp_ns2__leerImportesTotalesCliente01;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.27.113.11:20534/";
	soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__leerImportesTotalesCliente01.numerocliente = numerocliente;
	soap_tmp_ns2__leerImportesTotalesCliente01.Fecha = Fecha;
	soap_tmp_ns2__leerImportesTotalesCliente01.cIpCartera = cIpCartera;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__leerImportesTotalesCliente01(soap, &soap_tmp_ns2__leerImportesTotalesCliente01);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__leerImportesTotalesCliente01(soap, &soap_tmp_ns2__leerImportesTotalesCliente01, "ns2:leerImportesTotalesCliente01", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__leerImportesTotalesCliente01(soap, &soap_tmp_ns2__leerImportesTotalesCliente01, "ns2:leerImportesTotalesCliente01", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_13)
		return soap_closesock(soap);
	soap_default_ns2__leerImportesTotalesCliente01Response(soap, &_param_13);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns2__leerImportesTotalesCliente01Response(soap, &_param_13, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ccuentaProxy::leerConvenios01(int numerocliente, char *Fecha, char *cIpCartera, struct ns2__leerConvenios01Response &_param_14)
{	struct soap *soap = this;
	struct ns2__leerConvenios01 soap_tmp_ns2__leerConvenios01;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.27.113.11:20534/";
	soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__leerConvenios01.numerocliente = numerocliente;
	soap_tmp_ns2__leerConvenios01.Fecha = Fecha;
	soap_tmp_ns2__leerConvenios01.cIpCartera = cIpCartera;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__leerConvenios01(soap, &soap_tmp_ns2__leerConvenios01);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__leerConvenios01(soap, &soap_tmp_ns2__leerConvenios01, "ns2:leerConvenios01", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__leerConvenios01(soap, &soap_tmp_ns2__leerConvenios01, "ns2:leerConvenios01", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_14)
		return soap_closesock(soap);
	soap_default_ns2__leerConvenios01Response(soap, &_param_14);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns2__leerConvenios01Response(soap, &_param_14, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ccuentaProxy::leerCandidatosAumentoLRC(int numerocliente, char *Fecha, int Tienda, int ciudad, char *cIpCartera, struct ns2__leerCandidatosAumentoLRCResponse &_param_15)
{	struct soap *soap = this;
	struct ns2__leerCandidatosAumentoLRC soap_tmp_ns2__leerCandidatosAumentoLRC;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.27.113.11:20534/";
	soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__leerCandidatosAumentoLRC.numerocliente = numerocliente;
	soap_tmp_ns2__leerCandidatosAumentoLRC.Fecha = Fecha;
	soap_tmp_ns2__leerCandidatosAumentoLRC.Tienda = Tienda;
	soap_tmp_ns2__leerCandidatosAumentoLRC.ciudad = ciudad;
	soap_tmp_ns2__leerCandidatosAumentoLRC.cIpCartera = cIpCartera;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__leerCandidatosAumentoLRC(soap, &soap_tmp_ns2__leerCandidatosAumentoLRC);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__leerCandidatosAumentoLRC(soap, &soap_tmp_ns2__leerCandidatosAumentoLRC, "ns2:leerCandidatosAumentoLRC", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__leerCandidatosAumentoLRC(soap, &soap_tmp_ns2__leerCandidatosAumentoLRC, "ns2:leerCandidatosAumentoLRC", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_15)
		return soap_closesock(soap);
	soap_default_ns2__leerCandidatosAumentoLRCResponse(soap, &_param_15);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns2__leerCandidatosAumentoLRCResponse(soap, &_param_15, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ccuentaProxy::leerMargenCredito01(int numerocliente, char *Fecha, int Tienda, int ciudad, char *cIpCartera, struct ns2__leerMargenCredito01Response &_param_16)
{	struct soap *soap = this;
	struct ns2__leerMargenCredito01 soap_tmp_ns2__leerMargenCredito01;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.27.113.11:20534/";
	soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__leerMargenCredito01.numerocliente = numerocliente;
	soap_tmp_ns2__leerMargenCredito01.Fecha = Fecha;
	soap_tmp_ns2__leerMargenCredito01.Tienda = Tienda;
	soap_tmp_ns2__leerMargenCredito01.ciudad = ciudad;
	soap_tmp_ns2__leerMargenCredito01.cIpCartera = cIpCartera;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__leerMargenCredito01(soap, &soap_tmp_ns2__leerMargenCredito01);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__leerMargenCredito01(soap, &soap_tmp_ns2__leerMargenCredito01, "ns2:leerMargenCredito01", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__leerMargenCredito01(soap, &soap_tmp_ns2__leerMargenCredito01, "ns2:leerMargenCredito01", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_16)
		return soap_closesock(soap);
	soap_default_ns2__leerMargenCredito01Response(soap, &_param_16);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns2__leerMargenCredito01Response(soap, &_param_16, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ccuentaProxy::simularReestructuracion(int numerocliente, char *Fecha, char *cIpCartera, struct ns2__simularReestructuracionResponse &_param_17)
{	struct soap *soap = this;
	struct ns2__simularReestructuracion soap_tmp_ns2__simularReestructuracion;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.27.113.11:20534/";
	soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__simularReestructuracion.numerocliente = numerocliente;
	soap_tmp_ns2__simularReestructuracion.Fecha = Fecha;
	soap_tmp_ns2__simularReestructuracion.cIpCartera = cIpCartera;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__simularReestructuracion(soap, &soap_tmp_ns2__simularReestructuracion);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__simularReestructuracion(soap, &soap_tmp_ns2__simularReestructuracion, "ns2:simularReestructuracion", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__simularReestructuracion(soap, &soap_tmp_ns2__simularReestructuracion, "ns2:simularReestructuracion", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_17)
		return soap_closesock(soap);
	soap_default_ns2__simularReestructuracionResponse(soap, &_param_17);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns2__simularReestructuracionResponse(soap, &_param_17, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ccuentaProxy::leerBonificacionPrestamos(char *cDias, char *cInteresprestamo, char *cIplazo, char *cFechaPrestamo, char *cIpCartera, struct ns2__leerBonificacionPrestamosResponse &_param_18)
{	struct soap *soap = this;
	struct ns2__leerBonificacionPrestamos soap_tmp_ns2__leerBonificacionPrestamos;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.27.113.11:20534/";
	soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__leerBonificacionPrestamos.cDias = cDias;
	soap_tmp_ns2__leerBonificacionPrestamos.cInteresprestamo = cInteresprestamo;
	soap_tmp_ns2__leerBonificacionPrestamos.cIplazo = cIplazo;
	soap_tmp_ns2__leerBonificacionPrestamos.cFechaPrestamo = cFechaPrestamo;
	soap_tmp_ns2__leerBonificacionPrestamos.cIpCartera = cIpCartera;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__leerBonificacionPrestamos(soap, &soap_tmp_ns2__leerBonificacionPrestamos);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__leerBonificacionPrestamos(soap, &soap_tmp_ns2__leerBonificacionPrestamos, "ns2:leerBonificacionPrestamos", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__leerBonificacionPrestamos(soap, &soap_tmp_ns2__leerBonificacionPrestamos, "ns2:leerBonificacionPrestamos", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_18)
		return soap_closesock(soap);
	soap_default_ns2__leerBonificacionPrestamosResponse(soap, &_param_18);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns2__leerBonificacionPrestamosResponse(soap, &_param_18, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

void ccuentaProxy::soapError( void )
{
	struct soap *pSoap = this;		

	if (soap_check_state(pSoap ))
	{
		sprintf( cBufferError, "%s", "Error: soap struct not initialized\n" );
	}
	else
	{
		if (pSoap->error)
		{ 
			const char *pFaultCode = NULL, *pFaultSubCode = NULL, *pFalutString = NULL, **iFaultCode = NULL;
			iFaultCode = soap_faultcode(pSoap );
			if (!*iFaultCode)
				soap_set_fault(pSoap );
			pFaultCode = *iFaultCode;
			if (pSoap ->version == 2)
				pFaultSubCode = *soap_faultsubcode(pSoap );
			pFalutString = *soap_faultstring(pSoap );
			iFaultCode = soap_faultdetail(pSoap );

			//sprintf( cBufferError, "%s%d fault: %s [%s]\"%s\"Detail: %s", pSoap->version ? "SOAP 1." : "Error ", pSoap->version ? (int)pSoap->version : pSoap->error, pFaultCode, pFaultSubCode ? pFaultSubCode : "no subcode", pFalutString ? pFalutString : "[no reason]", iFaultCode && *iFaultCode ? *iFaultCode : "[no detail]" );
			sprintf( cBufferError, "%s", pFalutString ? pFalutString : "[no reason]" );
		}
	}	
}
const char *ccuentaProxy::obtenerError( void )
{ 
	soapError();
	return cBufferError;
}
/* End of client proxy code */
