/* soapStub.h
   Generated by gSOAP 2.8.12 from wsCCuenta.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_ns2	"urn:ccuenta"
#define SOAP_NAMESPACE_OF_ns1	"urn:ccuenta/ccuenta.wsdl"
#include "stdsoap2.h"
#if GSOAP_VERSION != 20812
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_ns2__DatoXml
#define SOAP_TYPE_ns2__DatoXml (7)
/* ns2:DatoXml */
class SOAP_CMAC ns2__DatoXml
{
public:
	char *Respuesta;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 7; } /* = unique id SOAP_TYPE_ns2__DatoXml */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns2__DatoXml() { ns2__DatoXml::soap_default(NULL); }
	virtual ~ns2__DatoXml() { }
};
#endif

#ifndef SOAP_TYPE_ns2__leerClienteCoppelResponse
#define SOAP_TYPE_ns2__leerClienteCoppelResponse (9)
/* ns2:leerClienteCoppelResponse */
struct ns2__leerClienteCoppelResponse
{
public:
	ns2__DatoXml *datos;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:DatoXml */
public:
	int soap_type() const { return 9; } /* = unique id SOAP_TYPE_ns2__leerClienteCoppelResponse */
};
#endif

#ifndef SOAP_TYPE_ns2__leerClienteCoppel
#define SOAP_TYPE_ns2__leerClienteCoppel (13)
/* ns2:leerClienteCoppel */
struct ns2__leerClienteCoppel
{
public:
	int numerocliente;	/* required element of type xsd:int */
	char *cIpCartera;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 13; } /* = unique id SOAP_TYPE_ns2__leerClienteCoppel */
};
#endif

#ifndef SOAP_TYPE_ns2__leerDatosClienteResponse
#define SOAP_TYPE_ns2__leerDatosClienteResponse (14)
/* ns2:leerDatosClienteResponse */
struct ns2__leerDatosClienteResponse
{
public:
	ns2__DatoXml *datos;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:DatoXml */
public:
	int soap_type() const { return 14; } /* = unique id SOAP_TYPE_ns2__leerDatosClienteResponse */
};
#endif

#ifndef SOAP_TYPE_ns2__leerDatosCliente
#define SOAP_TYPE_ns2__leerDatosCliente (17)
/* ns2:leerDatosCliente */
struct ns2__leerDatosCliente
{
public:
	int numerocliente;	/* required element of type xsd:int */
	char *tipoconsulta;	/* optional element of type xsd:string */
	char *cIpCartera;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 17; } /* = unique id SOAP_TYPE_ns2__leerDatosCliente */
};
#endif

#ifndef SOAP_TYPE_ns2__leerDomicilioClienteResponse
#define SOAP_TYPE_ns2__leerDomicilioClienteResponse (18)
/* ns2:leerDomicilioClienteResponse */
struct ns2__leerDomicilioClienteResponse
{
public:
	ns2__DatoXml *datos;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:DatoXml */
public:
	int soap_type() const { return 18; } /* = unique id SOAP_TYPE_ns2__leerDomicilioClienteResponse */
};
#endif

#ifndef SOAP_TYPE_ns2__leerDomicilioCliente
#define SOAP_TYPE_ns2__leerDomicilioCliente (21)
/* ns2:leerDomicilioCliente */
struct ns2__leerDomicilioCliente
{
public:
	int numerocliente;	/* required element of type xsd:int */
	char *cIpCartera;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 21; } /* = unique id SOAP_TYPE_ns2__leerDomicilioCliente */
};
#endif

#ifndef SOAP_TYPE_ns2__leerCuentasClienteResponse
#define SOAP_TYPE_ns2__leerCuentasClienteResponse (22)
/* ns2:leerCuentasClienteResponse */
struct ns2__leerCuentasClienteResponse
{
public:
	ns2__DatoXml *datos;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:DatoXml */
public:
	int soap_type() const { return 22; } /* = unique id SOAP_TYPE_ns2__leerCuentasClienteResponse */
};
#endif

#ifndef SOAP_TYPE_ns2__leerCuentasCliente
#define SOAP_TYPE_ns2__leerCuentasCliente (25)
/* ns2:leerCuentasCliente */
struct ns2__leerCuentasCliente
{
public:
	int numerocliente;	/* required element of type xsd:int */
	char *Fecha;	/* optional element of type xsd:string */
	char *cIpCartera;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 25; } /* = unique id SOAP_TYPE_ns2__leerCuentasCliente */
};
#endif

#ifndef SOAP_TYPE_ns2__leerCuentaClienteResponse
#define SOAP_TYPE_ns2__leerCuentaClienteResponse (26)
/* ns2:leerCuentaClienteResponse */
struct ns2__leerCuentaClienteResponse
{
public:
	ns2__DatoXml *datos;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:DatoXml */
public:
	int soap_type() const { return 26; } /* = unique id SOAP_TYPE_ns2__leerCuentaClienteResponse */
};
#endif

#ifndef SOAP_TYPE_ns2__leerCuentaCliente
#define SOAP_TYPE_ns2__leerCuentaCliente (29)
/* ns2:leerCuentaCliente */
struct ns2__leerCuentaCliente
{
public:
	int numerocliente;	/* required element of type xsd:int */
	char *Fecha;	/* optional element of type xsd:string */
	char *tipoconsulta;	/* optional element of type xsd:string */
	char *cIpCartera;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 29; } /* = unique id SOAP_TYPE_ns2__leerCuentaCliente */
};
#endif

#ifndef SOAP_TYPE_ns2__leerImportesTotalesClienteResponse
#define SOAP_TYPE_ns2__leerImportesTotalesClienteResponse (30)
/* ns2:leerImportesTotalesClienteResponse */
struct ns2__leerImportesTotalesClienteResponse
{
public:
	ns2__DatoXml *datos;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:DatoXml */
public:
	int soap_type() const { return 30; } /* = unique id SOAP_TYPE_ns2__leerImportesTotalesClienteResponse */
};
#endif

#ifndef SOAP_TYPE_ns2__leerImportesTotalesCliente
#define SOAP_TYPE_ns2__leerImportesTotalesCliente (33)
/* ns2:leerImportesTotalesCliente */
struct ns2__leerImportesTotalesCliente
{
public:
	int numerocliente;	/* required element of type xsd:int */
	char *Fecha;	/* optional element of type xsd:string */
	char *cIpCartera;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 33; } /* = unique id SOAP_TYPE_ns2__leerImportesTotalesCliente */
};
#endif

#ifndef SOAP_TYPE_ns2__leerImporteCandidatosPrestamosResponse
#define SOAP_TYPE_ns2__leerImporteCandidatosPrestamosResponse (34)
/* ns2:leerImporteCandidatosPrestamosResponse */
struct ns2__leerImporteCandidatosPrestamosResponse
{
public:
	ns2__DatoXml *datos;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:DatoXml */
public:
	int soap_type() const { return 34; } /* = unique id SOAP_TYPE_ns2__leerImporteCandidatosPrestamosResponse */
};
#endif

#ifndef SOAP_TYPE_ns2__leerImporteCandidatosPrestamos
#define SOAP_TYPE_ns2__leerImporteCandidatosPrestamos (37)
/* ns2:leerImporteCandidatosPrestamos */
struct ns2__leerImporteCandidatosPrestamos
{
public:
	int numerocliente;	/* required element of type xsd:int */
	char *Fecha;	/* optional element of type xsd:string */
	int Tienda;	/* required element of type xsd:int */
	int ciudad;	/* required element of type xsd:int */
	char *cIpCartera;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 37; } /* = unique id SOAP_TYPE_ns2__leerImporteCandidatosPrestamos */
};
#endif

#ifndef SOAP_TYPE_ns2__leerMargenCreditoResponse
#define SOAP_TYPE_ns2__leerMargenCreditoResponse (38)
/* ns2:leerMargenCreditoResponse */
struct ns2__leerMargenCreditoResponse
{
public:
	ns2__DatoXml *datos;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:DatoXml */
public:
	int soap_type() const { return 38; } /* = unique id SOAP_TYPE_ns2__leerMargenCreditoResponse */
};
#endif

#ifndef SOAP_TYPE_ns2__leerMargenCredito
#define SOAP_TYPE_ns2__leerMargenCredito (41)
/* ns2:leerMargenCredito */
struct ns2__leerMargenCredito
{
public:
	int numerocliente;	/* required element of type xsd:int */
	char *Fecha;	/* optional element of type xsd:string */
	int Tienda;	/* required element of type xsd:int */
	int ciudad;	/* required element of type xsd:int */
	char *cIpCartera;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 41; } /* = unique id SOAP_TYPE_ns2__leerMargenCredito */
};
#endif

#ifndef SOAP_TYPE_ns2__leerConveniosResponse
#define SOAP_TYPE_ns2__leerConveniosResponse (42)
/* ns2:leerConveniosResponse */
struct ns2__leerConveniosResponse
{
public:
	ns2__DatoXml *datos;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:DatoXml */
public:
	int soap_type() const { return 42; } /* = unique id SOAP_TYPE_ns2__leerConveniosResponse */
};
#endif

#ifndef SOAP_TYPE_ns2__leerConvenios
#define SOAP_TYPE_ns2__leerConvenios (45)
/* ns2:leerConvenios */
struct ns2__leerConvenios
{
public:
	int numerocliente;	/* required element of type xsd:int */
	char *Fecha;	/* optional element of type xsd:string */
	char *cIpCartera;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 45; } /* = unique id SOAP_TYPE_ns2__leerConvenios */
};
#endif

#ifndef SOAP_TYPE_ns2__leerCantidadCuentasActivasResponse
#define SOAP_TYPE_ns2__leerCantidadCuentasActivasResponse (46)
/* ns2:leerCantidadCuentasActivasResponse */
struct ns2__leerCantidadCuentasActivasResponse
{
public:
	ns2__DatoXml *datos;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:DatoXml */
public:
	int soap_type() const { return 46; } /* = unique id SOAP_TYPE_ns2__leerCantidadCuentasActivasResponse */
};
#endif

#ifndef SOAP_TYPE_ns2__leerCantidadCuentasActivas
#define SOAP_TYPE_ns2__leerCantidadCuentasActivas (49)
/* ns2:leerCantidadCuentasActivas */
struct ns2__leerCantidadCuentasActivas
{
public:
	int numerocliente;	/* required element of type xsd:int */
	char *Fecha;	/* optional element of type xsd:string */
	char *cIpCartera;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 49; } /* = unique id SOAP_TYPE_ns2__leerCantidadCuentasActivas */
};
#endif

#ifndef SOAP_TYPE_ns2__leerCuentaCliente01Response
#define SOAP_TYPE_ns2__leerCuentaCliente01Response (50)
/* ns2:leerCuentaCliente01Response */
struct ns2__leerCuentaCliente01Response
{
public:
	ns2__DatoXml *datos;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:DatoXml */
public:
	int soap_type() const { return 50; } /* = unique id SOAP_TYPE_ns2__leerCuentaCliente01Response */
};
#endif

#ifndef SOAP_TYPE_ns2__leerCuentaCliente01
#define SOAP_TYPE_ns2__leerCuentaCliente01 (53)
/* ns2:leerCuentaCliente01 */
struct ns2__leerCuentaCliente01
{
public:
	int numerocliente;	/* required element of type xsd:int */
	char *Fecha;	/* optional element of type xsd:string */
	char *tipoconsulta;	/* optional element of type xsd:string */
	char *cIpCartera;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 53; } /* = unique id SOAP_TYPE_ns2__leerCuentaCliente01 */
};
#endif

#ifndef SOAP_TYPE_ns2__leerCuentasCliente01Response
#define SOAP_TYPE_ns2__leerCuentasCliente01Response (54)
/* ns2:leerCuentasCliente01Response */
struct ns2__leerCuentasCliente01Response
{
public:
	ns2__DatoXml *datos;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:DatoXml */
public:
	int soap_type() const { return 54; } /* = unique id SOAP_TYPE_ns2__leerCuentasCliente01Response */
};
#endif

#ifndef SOAP_TYPE_ns2__leerCuentasCliente01
#define SOAP_TYPE_ns2__leerCuentasCliente01 (57)
/* ns2:leerCuentasCliente01 */
struct ns2__leerCuentasCliente01
{
public:
	int numerocliente;	/* required element of type xsd:int */
	char *Fecha;	/* optional element of type xsd:string */
	char *cIpCartera;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 57; } /* = unique id SOAP_TYPE_ns2__leerCuentasCliente01 */
};
#endif

#ifndef SOAP_TYPE_ns2__leerImportesTotalesCliente01Response
#define SOAP_TYPE_ns2__leerImportesTotalesCliente01Response (58)
/* ns2:leerImportesTotalesCliente01Response */
struct ns2__leerImportesTotalesCliente01Response
{
public:
	ns2__DatoXml *datos;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:DatoXml */
public:
	int soap_type() const { return 58; } /* = unique id SOAP_TYPE_ns2__leerImportesTotalesCliente01Response */
};
#endif

#ifndef SOAP_TYPE_ns2__leerImportesTotalesCliente01
#define SOAP_TYPE_ns2__leerImportesTotalesCliente01 (61)
/* ns2:leerImportesTotalesCliente01 */
struct ns2__leerImportesTotalesCliente01
{
public:
	int numerocliente;	/* required element of type xsd:int */
	char *Fecha;	/* optional element of type xsd:string */
	char *cIpCartera;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 61; } /* = unique id SOAP_TYPE_ns2__leerImportesTotalesCliente01 */
};
#endif

#ifndef SOAP_TYPE_ns2__leerConvenios01Response
#define SOAP_TYPE_ns2__leerConvenios01Response (62)
/* ns2:leerConvenios01Response */
struct ns2__leerConvenios01Response
{
public:
	ns2__DatoXml *datos;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:DatoXml */
public:
	int soap_type() const { return 62; } /* = unique id SOAP_TYPE_ns2__leerConvenios01Response */
};
#endif

#ifndef SOAP_TYPE_ns2__leerConvenios01
#define SOAP_TYPE_ns2__leerConvenios01 (65)
/* ns2:leerConvenios01 */
struct ns2__leerConvenios01
{
public:
	int numerocliente;	/* required element of type xsd:int */
	char *Fecha;	/* optional element of type xsd:string */
	char *cIpCartera;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 65; } /* = unique id SOAP_TYPE_ns2__leerConvenios01 */
};
#endif

#ifndef SOAP_TYPE_ns2__leerCandidatosAumentoLRCResponse
#define SOAP_TYPE_ns2__leerCandidatosAumentoLRCResponse (66)
/* ns2:leerCandidatosAumentoLRCResponse */
struct ns2__leerCandidatosAumentoLRCResponse
{
public:
	ns2__DatoXml *datos;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:DatoXml */
public:
	int soap_type() const { return 66; } /* = unique id SOAP_TYPE_ns2__leerCandidatosAumentoLRCResponse */
};
#endif

#ifndef SOAP_TYPE_ns2__leerCandidatosAumentoLRC
#define SOAP_TYPE_ns2__leerCandidatosAumentoLRC (69)
/* ns2:leerCandidatosAumentoLRC */
struct ns2__leerCandidatosAumentoLRC
{
public:
	int numerocliente;	/* required element of type xsd:int */
	char *Fecha;	/* optional element of type xsd:string */
	int Tienda;	/* required element of type xsd:int */
	int ciudad;	/* required element of type xsd:int */
	char *cIpCartera;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 69; } /* = unique id SOAP_TYPE_ns2__leerCandidatosAumentoLRC */
};
#endif

#ifndef SOAP_TYPE_ns2__leerMargenCredito01Response
#define SOAP_TYPE_ns2__leerMargenCredito01Response (70)
/* ns2:leerMargenCredito01Response */
struct ns2__leerMargenCredito01Response
{
public:
	ns2__DatoXml *datos;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:DatoXml */
public:
	int soap_type() const { return 70; } /* = unique id SOAP_TYPE_ns2__leerMargenCredito01Response */
};
#endif

#ifndef SOAP_TYPE_ns2__leerMargenCredito01
#define SOAP_TYPE_ns2__leerMargenCredito01 (73)
/* ns2:leerMargenCredito01 */
struct ns2__leerMargenCredito01
{
public:
	int numerocliente;	/* required element of type xsd:int */
	char *Fecha;	/* optional element of type xsd:string */
	int Tienda;	/* required element of type xsd:int */
	int ciudad;	/* required element of type xsd:int */
	char *cIpCartera;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 73; } /* = unique id SOAP_TYPE_ns2__leerMargenCredito01 */
};
#endif

#ifndef SOAP_TYPE_ns2__simularReestructuracionResponse
#define SOAP_TYPE_ns2__simularReestructuracionResponse (74)
/* ns2:simularReestructuracionResponse */
struct ns2__simularReestructuracionResponse
{
public:
	ns2__DatoXml *datos;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:DatoXml */
public:
	int soap_type() const { return 74; } /* = unique id SOAP_TYPE_ns2__simularReestructuracionResponse */
};
#endif

#ifndef SOAP_TYPE_ns2__simularReestructuracion
#define SOAP_TYPE_ns2__simularReestructuracion (77)
/* ns2:simularReestructuracion */
struct ns2__simularReestructuracion
{
public:
	int numerocliente;	/* required element of type xsd:int */
	char *Fecha;	/* optional element of type xsd:string */
	char *cIpCartera;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 77; } /* = unique id SOAP_TYPE_ns2__simularReestructuracion */
};
#endif

#ifndef SOAP_TYPE_ns2__leerBonificacionPrestamosResponse
#define SOAP_TYPE_ns2__leerBonificacionPrestamosResponse (78)
/* ns2:leerBonificacionPrestamosResponse */
struct ns2__leerBonificacionPrestamosResponse
{
public:
	ns2__DatoXml *datos;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:DatoXml */
public:
	int soap_type() const { return 78; } /* = unique id SOAP_TYPE_ns2__leerBonificacionPrestamosResponse */
};
#endif

#ifndef SOAP_TYPE_ns2__leerBonificacionPrestamos
#define SOAP_TYPE_ns2__leerBonificacionPrestamos (81)
/* ns2:leerBonificacionPrestamos */
struct ns2__leerBonificacionPrestamos
{
public:
	char *cDias;	/* optional element of type xsd:string */
	char *cInteresprestamo;	/* optional element of type xsd:string */
	char *cIplazo;	/* optional element of type xsd:string */
	char *cFechaPrestamo;	/* optional element of type xsd:string */
	char *cIpCartera;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 81; } /* = unique id SOAP_TYPE_ns2__leerBonificacionPrestamos */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (82)
/* SOAP Header: */
struct SOAP_ENV__Header
{
public:
	int soap_type() const { return 82; } /* = unique id SOAP_TYPE_SOAP_ENV__Header */
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (83)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
public:
	int soap_type() const { return 83; } /* = unique id SOAP_TYPE_SOAP_ENV__Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (85)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
public:
	int soap_type() const { return 85; } /* = unique id SOAP_TYPE_SOAP_ENV__Detail */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (88)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 88; } /* = unique id SOAP_TYPE_SOAP_ENV__Reason */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (89)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
public:
	int soap_type() const { return 89; } /* = unique id SOAP_TYPE_SOAP_ENV__Fault */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 ns2__leerClienteCoppel(struct soap*, int numerocliente, char *cIpCartera, struct ns2__leerClienteCoppelResponse &_param_1);

SOAP_FMAC5 int SOAP_FMAC6 ns2__leerDatosCliente(struct soap*, int numerocliente, char *tipoconsulta, char *cIpCartera, struct ns2__leerDatosClienteResponse &_param_2);

SOAP_FMAC5 int SOAP_FMAC6 ns2__leerDomicilioCliente(struct soap*, int numerocliente, char *cIpCartera, struct ns2__leerDomicilioClienteResponse &_param_3);

SOAP_FMAC5 int SOAP_FMAC6 ns2__leerCuentasCliente(struct soap*, int numerocliente, char *Fecha, char *cIpCartera, struct ns2__leerCuentasClienteResponse &_param_4);

SOAP_FMAC5 int SOAP_FMAC6 ns2__leerCuentaCliente(struct soap*, int numerocliente, char *Fecha, char *tipoconsulta, char *cIpCartera, struct ns2__leerCuentaClienteResponse &_param_5);

SOAP_FMAC5 int SOAP_FMAC6 ns2__leerImportesTotalesCliente(struct soap*, int numerocliente, char *Fecha, char *cIpCartera, struct ns2__leerImportesTotalesClienteResponse &_param_6);

SOAP_FMAC5 int SOAP_FMAC6 ns2__leerImporteCandidatosPrestamos(struct soap*, int numerocliente, char *Fecha, int Tienda, int ciudad, char *cIpCartera, struct ns2__leerImporteCandidatosPrestamosResponse &_param_7);

SOAP_FMAC5 int SOAP_FMAC6 ns2__leerMargenCredito(struct soap*, int numerocliente, char *Fecha, int Tienda, int ciudad, char *cIpCartera, struct ns2__leerMargenCreditoResponse &_param_8);

SOAP_FMAC5 int SOAP_FMAC6 ns2__leerConvenios(struct soap*, int numerocliente, char *Fecha, char *cIpCartera, struct ns2__leerConveniosResponse &_param_9);

SOAP_FMAC5 int SOAP_FMAC6 ns2__leerCantidadCuentasActivas(struct soap*, int numerocliente, char *Fecha, char *cIpCartera, struct ns2__leerCantidadCuentasActivasResponse &_param_10);

SOAP_FMAC5 int SOAP_FMAC6 ns2__leerCuentaCliente01(struct soap*, int numerocliente, char *Fecha, char *tipoconsulta, char *cIpCartera, struct ns2__leerCuentaCliente01Response &_param_11);

SOAP_FMAC5 int SOAP_FMAC6 ns2__leerCuentasCliente01(struct soap*, int numerocliente, char *Fecha, char *cIpCartera, struct ns2__leerCuentasCliente01Response &_param_12);

SOAP_FMAC5 int SOAP_FMAC6 ns2__leerImportesTotalesCliente01(struct soap*, int numerocliente, char *Fecha, char *cIpCartera, struct ns2__leerImportesTotalesCliente01Response &_param_13);

SOAP_FMAC5 int SOAP_FMAC6 ns2__leerConvenios01(struct soap*, int numerocliente, char *Fecha, char *cIpCartera, struct ns2__leerConvenios01Response &_param_14);

SOAP_FMAC5 int SOAP_FMAC6 ns2__leerCandidatosAumentoLRC(struct soap*, int numerocliente, char *Fecha, int Tienda, int ciudad, char *cIpCartera, struct ns2__leerCandidatosAumentoLRCResponse &_param_15);

SOAP_FMAC5 int SOAP_FMAC6 ns2__leerMargenCredito01(struct soap*, int numerocliente, char *Fecha, int Tienda, int ciudad, char *cIpCartera, struct ns2__leerMargenCredito01Response &_param_16);

SOAP_FMAC5 int SOAP_FMAC6 ns2__simularReestructuracion(struct soap*, int numerocliente, char *Fecha, char *cIpCartera, struct ns2__simularReestructuracionResponse &_param_17);

SOAP_FMAC5 int SOAP_FMAC6 ns2__leerBonificacionPrestamos(struct soap*, char *cDias, char *cInteresprestamo, char *cIplazo, char *cFechaPrestamo, char *cIpCartera, struct ns2__leerBonificacionPrestamosResponse &_param_18);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__leerClienteCoppel(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__leerDatosCliente(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__leerDomicilioCliente(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__leerCuentasCliente(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__leerCuentaCliente(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__leerImportesTotalesCliente(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__leerImporteCandidatosPrestamos(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__leerMargenCredito(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__leerConvenios(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__leerCantidadCuentasActivas(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__leerCuentaCliente01(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__leerCuentasCliente01(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__leerImportesTotalesCliente01(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__leerConvenios01(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__leerCandidatosAumentoLRC(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__leerMargenCredito01(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__simularReestructuracion(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__leerBonificacionPrestamos(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__leerClienteCoppel(struct soap *soap, const char *soap_endpoint, const char *soap_action, int numerocliente, char *cIpCartera, struct ns2__leerClienteCoppelResponse &_param_1);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__leerDatosCliente(struct soap *soap, const char *soap_endpoint, const char *soap_action, int numerocliente, char *tipoconsulta, char *cIpCartera, struct ns2__leerDatosClienteResponse &_param_2);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__leerDomicilioCliente(struct soap *soap, const char *soap_endpoint, const char *soap_action, int numerocliente, char *cIpCartera, struct ns2__leerDomicilioClienteResponse &_param_3);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__leerCuentasCliente(struct soap *soap, const char *soap_endpoint, const char *soap_action, int numerocliente, char *Fecha, char *cIpCartera, struct ns2__leerCuentasClienteResponse &_param_4);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__leerCuentaCliente(struct soap *soap, const char *soap_endpoint, const char *soap_action, int numerocliente, char *Fecha, char *tipoconsulta, char *cIpCartera, struct ns2__leerCuentaClienteResponse &_param_5);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__leerImportesTotalesCliente(struct soap *soap, const char *soap_endpoint, const char *soap_action, int numerocliente, char *Fecha, char *cIpCartera, struct ns2__leerImportesTotalesClienteResponse &_param_6);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__leerImporteCandidatosPrestamos(struct soap *soap, const char *soap_endpoint, const char *soap_action, int numerocliente, char *Fecha, int Tienda, int ciudad, char *cIpCartera, struct ns2__leerImporteCandidatosPrestamosResponse &_param_7);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__leerMargenCredito(struct soap *soap, const char *soap_endpoint, const char *soap_action, int numerocliente, char *Fecha, int Tienda, int ciudad, char *cIpCartera, struct ns2__leerMargenCreditoResponse &_param_8);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__leerConvenios(struct soap *soap, const char *soap_endpoint, const char *soap_action, int numerocliente, char *Fecha, char *cIpCartera, struct ns2__leerConveniosResponse &_param_9);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__leerCantidadCuentasActivas(struct soap *soap, const char *soap_endpoint, const char *soap_action, int numerocliente, char *Fecha, char *cIpCartera, struct ns2__leerCantidadCuentasActivasResponse &_param_10);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__leerCuentaCliente01(struct soap *soap, const char *soap_endpoint, const char *soap_action, int numerocliente, char *Fecha, char *tipoconsulta, char *cIpCartera, struct ns2__leerCuentaCliente01Response &_param_11);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__leerCuentasCliente01(struct soap *soap, const char *soap_endpoint, const char *soap_action, int numerocliente, char *Fecha, char *cIpCartera, struct ns2__leerCuentasCliente01Response &_param_12);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__leerImportesTotalesCliente01(struct soap *soap, const char *soap_endpoint, const char *soap_action, int numerocliente, char *Fecha, char *cIpCartera, struct ns2__leerImportesTotalesCliente01Response &_param_13);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__leerConvenios01(struct soap *soap, const char *soap_endpoint, const char *soap_action, int numerocliente, char *Fecha, char *cIpCartera, struct ns2__leerConvenios01Response &_param_14);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__leerCandidatosAumentoLRC(struct soap *soap, const char *soap_endpoint, const char *soap_action, int numerocliente, char *Fecha, int Tienda, int ciudad, char *cIpCartera, struct ns2__leerCandidatosAumentoLRCResponse &_param_15);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__leerMargenCredito01(struct soap *soap, const char *soap_endpoint, const char *soap_action, int numerocliente, char *Fecha, int Tienda, int ciudad, char *cIpCartera, struct ns2__leerMargenCredito01Response &_param_16);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__simularReestructuracion(struct soap *soap, const char *soap_endpoint, const char *soap_action, int numerocliente, char *Fecha, char *cIpCartera, struct ns2__simularReestructuracionResponse &_param_17);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__leerBonificacionPrestamos(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *cDias, char *cInteresprestamo, char *cIplazo, char *cFechaPrestamo, char *cIpCartera, struct ns2__leerBonificacionPrestamosResponse &_param_18);

#endif

/* End of soapStub.h */
