//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CapturarAbono.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_DLGREESTRUCTURA             108
#define IDD_DLG_CAPTURAABONOCELULARES   111
#define IDC_INTMESUNO                   1000
#define IDC_MSGCANDIDATOREESTRUCTURA    1001
#define IDC_COMBO1                      1014
#define IDC_MENSAJE2                    1015
#define IDC_MENSAJE3                    1016
#define ID_CANCELAR                     1017
#define ID_REESTRUCTURA                 1018
#define IDC_MSGREESTRUCTURA             1019
#define IDC_MSGDINEROELECTRONICO        1020
#define IDC_MSGABONOSPUNTUALES          1021
#define IDC_ABONOSPUNTUALES             1022
#define IDC_LEYENDA_ACLARACIONSDO       1028
#define IDC_TXT_MESES                   1029
#define IDC_EDIT2                       1030
#define IDC_LBL_BARRA                   1031
#define IDC_LBL_TEXTO                   1032
#define IDD_ABOUTBOX                    4569
#define IDS_ABOUTBOX                    4570
#define IDD_DLGCAPTURARABONO            4571
#define IDD_DLGCAPTURARCLIENTEETP       4572
#define IDD_DLGCAPTURAREMPLEADOSUPERVISOR 4574
#define IDD_DLGCAPTURARCONVENIO         4575
#define IDD_DLGCAPTURARDATOSSEGURO      4576
#define IDD_DLGENCUESTA                 4577
#define IDC_CLIENTE                     4580
#define IDC_PUNTUALIDAD                 4581
#define IDC_APELLIDOPATERNO             4582
#define IDC_APELLIDOMATERNO             4583
#define IDC_NOMBRE                      4584
#define IDC_GRID                        4585
#define IDC_PUNTUALIZAD2                4587
#define IDC_GRID2                       4588
#define IDC_ENTREGO                     4590
#define IDC_MENSAJE                     4591
#define IDC_FLECHA                      4592
#define IDC_CLIENTEETP                  4593
#define IDC_EMPLEADOSUPERVISOR          4594
#define IDC_PLAZO                       4595
#define IDC_IMPORTE                     4596
#define IDC_EMPLEADO                    4597
#define IDC_CANCELAR                    4598
#define IDC_ACEPTAR                     4600
#define IDC_MESES                       4601
#define IDC_SEGUROS                     4602
#define IDC_APELLIDOPATERNO2            4603
#define IDC_APELLIDOMATERNO2            4604
#define IDC_ZONA                        4605
#define IDC_TELEFONO2                   4606
#define IDC_NUMEROZONA                  4607
#define IDC_TELEFONO                    4608
#define IDC_NOMBRE2                     4609
#define IDC_ENCABEZADO                  4611
#define IDC_CALLE                       4612
#define IDC_COLONIA                     4613
#define IDC_CASA                        4614
#define IDC_RUMBO                       4615
#define IDC_SEXO2                       4616
#define IDC_CELULAR                     4617
#define IDC_FECHANACIMIENTO             4618
#define IDC_ESTADOCIVIL                 4619
#define IDC_INGRESO                     4620
#define IDC_COMPLEMENTO                 4621
#define IDC_VIVEDESDE                   4622
#define IDC_PERSONASTRABAJAN            4623
#define IDC_TRABAJADESDE                4624
#define IDC_PUESTO                      4625
#define IDC_CASAPRF2                    4626
#define IDC_MES                         4627
#define IDC_ANIO                        4628
#define IDC_NOPIDEDATOS                 4629
#define IDC_TELEFONOTRABAJO             4630
#define IDC_CAMBIO                      4631
#define IDC_NOMBRECOLONIA               4632
#define IDC_EDAD                        4633
#define IDC_MSGMINIMO                   4634
#define IDC_MSGMINIMO2                  4635
#define IDC_MSGMINIMO3                  4636
#define IDC_ASTERISCOCOPPEL             4637
#define IDC_STATIC_CLIENTE              4638
#define IDC_STATIC_ENTREGO              4639
#define IDC_STATIC_CAMBIO               4640
#define IDC_DINEROELECTRONICO           4640
#define IDC_STATIC_CLIENTE2             4641
#define IDC_STATIC_EMPLEADO3            4642
#define IDC_STATIC_PLAZO3               4643
#define IDC_STATIC_IMPORTE3             4644
#define IDC_STATIC_CLIENTE4             4645
#define IDC_STATIC_CALLE4               4646
#define IDC_STATIC_COLONIA4             4647
#define IDC_STATIC_CASA4                4649
#define IDC_STATIC_CASAPRF4             4650
#define IDC_STATIC_TELEFONO4            4651
#define IDC_STATIC_SEXO4                4652
#define IDC_STATIC_RUMBO4               4653
#define IDC_STATIC_CEL4                 4654
#define IDC_STATIC_FECHANAC4            4655
#define IDC_STATIC_ESTADOCIVIL4         4656
#define IDC_STATIC_INGRESO4             4657
#define IDC_STATIC_COMPLEMENTO4         4658
#define IDC_STATIC_PERSONASTRAB4        4659
#define IDC_STATIC_VIVEDESDE4           4660
#define IDC_STATIC_TRABAJADESDE4        4661
#define IDC_STATIC_PUESTO4              4662
#define IDC_STATIC_FORMATOFECHA4        4663
#define IDC_STATIC_TELTRABAJO4          4664
#define IDC_STATIC_SEGUROS5             4665
#define IDC_STATIC_MESES5               4666
#define IDC_STATIC_EMPLEADO6            4667
#define IDC_STATIC_COLONIA              4668
#define IDC_CORREO                      4669
#define IDC_LBLCORREO                   4670
#define IDC_CELULARCLIENTE              4671
#define IDC_LBLCELULAR                  4672
#define IDC_STATIC_MENSAJECREZCASUHOGAR 6368
#define IDD_DLGCAPTURARCAMBIOSEGURO     6369
#define IDC_STATIC_ASEGURADOS           6370
#define IDC_ASEGURADOS                  6371
#define IDC_SEGUROS2                    6372
#define IDC_FECHANACIMIENTOADIC         6373
#define IDD_DLGCAPTURARDATOSSEGUROMOTOS 6374

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        112
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1029
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
